# API Gateway - Production Configuration (Faza 14 - Security Enhancement)

server:
  port: 8080
  ssl:
    enabled: true
    key-store: file:/etc/car-sharing/certs/api-gateway.p12
    key-store-password: ${KEYSTORE_PASSWORD} # from Vault
    key-store-type: PKCS12
    key-alias: api-gateway
    
    # mTLS - require client certificates for service-to-service communication
    client-auth: need
    trust-store: file:/etc/car-sharing/certs/truststore.p12
    trust-store-password: ${TRUSTSTORE_PASSWORD} # from Vault
    trust-store-type: PKCS12

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false # Use explicit routes in prod (no auto-discovery)
          lower-case-service-id: true

# CORS Configuration - Production (Strict Whitelist)
cors:
  allowed-origins: "https://app.carsharing.com,https://admin.carsharing.com"
  allowed-methods: "GET,POST,PUT,DELETE"
  allowed-headers: "Authorization,Content-Type,X-Request-Id,X-Idempotency-Key"
  max-age: 7200 # 2 hours cache for preflight
  allow-credentials: true # Required for JWT cookies
  exposed-headers: "X-Total-Count,X-Request-Id,X-Trace-Id"

# Rate Limiting (Production Thresholds)
ratelimit:
  enabled: true
  default-capacity: 50 # Max 50 requests in burst
  default-refill-rate: 20 # 20 requests per second per user

# Security Headers
security:
  headers:
    hsts:
      enabled: true
      include-subdomains: true
      max-age: 31536000 # 1 year
      preload: true
    frame-options:
      mode: DENY
    content-type-options:
      enabled: true
    xss-protection:
      enabled: true
      block: true

# Actuator (Minimal exposure in prod)
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: when-authorized # Require authentication to see details

# Logging (Reduced verbosity in prod)
logging:
  level:
    root: WARN
    com.services: INFO
    org.springframework.cloud.gateway: WARN
    org.springframework.security: WARN
