# API Gateway specific configuration

server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

# CORS configuration (to be detailed in Faza 2 implementation)
cors:
  allowed-origins: "http://localhost:4200"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  max-age: 3600

# Rate limiting (to be implemented with Redis)
ratelimit:
  enabled: true
  default-capacity: 100
  default-refill-rate: 10
