-- Flyway migration V1__init.sql for Feedback Service
-- Schema: feedback
-- Author: Car Sharing Team
-- Date: 2025-11-07

-- =============================================================================
-- STEP 1: Schema and Extensions
-- =============================================================================

-- Create feedback schema
CREATE SCHEMA IF NOT EXISTS feedback;

-- Extension citext for case-insensitive text (not strictly needed for feedback but following pattern)
-- Note: citext may already exist from previous migrations (identity/car/pricing/rental)
CREATE EXTENSION IF NOT EXISTS citext;

-- =============================================================================
-- STEP 2: Audit Trigger Function (shared across all services)
-- =============================================================================

-- Create audit trigger function if not exists (idempotent)
-- This function auto-populates created_date, created_by, last_modified_date, last_modified_by
CREATE OR REPLACE FUNCTION public.set_audit_fields() RETURNS trigger AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    NEW.created_date := COALESCE(NEW.created_date, now());
    NEW.created_by   := COALESCE(NEW.created_by, current_setting('app.current_account_id', true), 'system');
  END IF;
  NEW.last_modified_date := now();
  NEW.last_modified_by   := COALESCE(current_setting('app.current_account_id', true), NEW.last_modified_by, NEW.created_by, 'system');
  RETURN NEW;
END
$$ LANGUAGE plpgsql;

-- =============================================================================
-- STEP 3: Feedback Table
-- =============================================================================

CREATE TABLE IF NOT EXISTS feedback.cars_feedback (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  -- Rating (0.0 to 5.0)
  rating DOUBLE PRECISION NOT NULL CHECK (rating BETWEEN 0 AND 5),
  
  -- Optional comment
  comment TEXT,
  
  -- Foreign key to car.cars.id (ON DELETE CASCADE)
  cars_id BIGINT NOT NULL,
  
  -- Foreign key to identity.accounts.id (ON DELETE SET NULL for anonymization)
  reviewer_id VARCHAR(255),
  
  -- Audit fields
  created_date TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_modified_date TIMESTAMPTZ,
  created_by VARCHAR(255) NOT NULL DEFAULT 'system',
  last_modified_by VARCHAR(255),
  
  -- Foreign key constraints
  -- Note: We assume car.cars and identity.accounts exist from previous migrations
  -- In production, verify cross-schema FKs are supported or manage referential integrity in application layer
  CONSTRAINT fk_feedback_cars FOREIGN KEY (cars_id) REFERENCES car.cars(id) ON DELETE CASCADE,
  CONSTRAINT fk_feedback_reviewer FOREIGN KEY (reviewer_id) REFERENCES identity.accounts(id) ON DELETE SET NULL
);

-- =============================================================================
-- STEP 4: Audit Trigger
-- =============================================================================

CREATE TRIGGER trg_feedback_audit
BEFORE INSERT OR UPDATE ON feedback.cars_feedback
FOR EACH ROW EXECUTE FUNCTION public.set_audit_fields();

-- =============================================================================
-- STEP 5: Indexes
-- =============================================================================

-- Index on cars_id for fast lookups (most common query: feedback by car)
CREATE INDEX IF NOT EXISTS idx_feedback_cars_id ON feedback.cars_feedback(cars_id);

-- Index on reviewer_id for user profile queries
CREATE INDEX IF NOT EXISTS idx_feedback_reviewer_id ON feedback.cars_feedback(reviewer_id);

-- Index on created_date for recent feedback queries (admin dashboard)
CREATE INDEX IF NOT EXISTS idx_feedback_created_date ON feedback.cars_feedback(created_date DESC);

-- Composite index for anti-abuse duplicate prevention (cars_id, reviewer_id)
CREATE INDEX IF NOT EXISTS idx_feedback_car_reviewer ON feedback.cars_feedback(cars_id, reviewer_id);

-- Index on rating for aggregation queries (average, distribution)
CREATE INDEX IF NOT EXISTS idx_feedback_rating ON feedback.cars_feedback(rating);

-- =============================================================================
-- STEP 6: Outbox Table (Event Sourcing)
-- =============================================================================

CREATE TABLE IF NOT EXISTS feedback.outbox_event (
  id UUID PRIMARY KEY,
  aggregate_type VARCHAR(100) NOT NULL,
  aggregate_id VARCHAR(100) NOT NULL,
  payload JSONB NOT NULL,
  headers JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  published_at TIMESTAMPTZ,
  status VARCHAR(20) NOT NULL DEFAULT 'NEW',
  CONSTRAINT chk_feedback_outbox_status CHECK (status IN ('NEW','PUBLISHED','FAILED'))
);

CREATE INDEX IF NOT EXISTS idx_feedback_outbox_status_created ON feedback.outbox_event(status, created_at);
CREATE INDEX IF NOT EXISTS idx_feedback_outbox_new ON feedback.outbox_event(status) WHERE status = 'NEW';

-- =============================================================================
-- STEP 7: Role and Grants
-- =============================================================================

-- Create role for feedback_service (idempotent)
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'feedback_service') THEN
    CREATE ROLE feedback_service NOLOGIN;
  END IF;
END $$;

-- Grant schema usage
GRANT USAGE ON SCHEMA feedback TO feedback_service;

-- Grant table permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA feedback TO feedback_service;

-- Grant sequence permissions (for IDENTITY columns)
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA feedback TO feedback_service;

-- =============================================================================
-- STEP 8: Row-Level Security (Optional, for multi-tenant scenarios)
-- =============================================================================

-- Note: RLS not strictly needed for feedback (public read, authenticated write)
-- If needed in future, enable with:
-- ALTER TABLE feedback.cars_feedback ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY feedback_select_public ON feedback.cars_feedback FOR SELECT USING (TRUE);
-- CREATE POLICY feedback_modify_own ON feedback.cars_feedback FOR UPDATE, DELETE USING (reviewer_id = current_setting('app.current_account_id', true));

-- =============================================================================
-- Migration complete
-- =============================================================================
