-- =====================================================
-- Flyway Migration V1: Car Service Schema Initialization
-- =====================================================
-- Description: Creates the 'car' schema with all necessary tables,
--              types, constraints, indexes, triggers, and permissions
--              for the Car Management Service.
-- 
-- Author: Car Sharing Team
-- Version: 1.0
-- Date: 2025-11-06
-- =====================================================

-- Set timezone to UTC (recommended for all timestamps)
SET TIME ZONE 'UTC';

-- =====================================================
-- 1. Schema Creation
-- =====================================================

CREATE SCHEMA IF NOT EXISTS car;

-- =====================================================
-- 2. Extensions (if not already installed globally)
-- =====================================================

-- btree_gist: Required for EXCLUDE constraints with '=' operators
CREATE EXTENSION IF NOT EXISTS btree_gist;

-- citext: Case-insensitive text type for registration_number
CREATE EXTENSION IF NOT EXISTS citext;

-- =====================================================
-- 3. Enum Types (shared with other services)
-- =====================================================

-- Vehicle category for pricing tier
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'vehicle_category') THEN
    CREATE TYPE vehicle_category AS ENUM ('ECONOM', 'STANDARD', 'PREMIUM');
  END IF;
END $$;

-- Transmission type
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'transmission_type') THEN
    CREATE TYPE transmission_type AS ENUM ('MANUAL', 'AUTOMATIC');
  END IF;
END $$;

-- Fuel type
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'fuel_type') THEN
    CREATE TYPE fuel_type AS ENUM ('GASOLINE', 'DIESEL', 'ELECTRIC', 'HYBRID', 'PLUG_IN_HYBRID');
  END IF;
END $$;

-- =====================================================
-- 4. Audit Trigger Function (shared, idempotent)
-- =====================================================

CREATE OR REPLACE FUNCTION public.set_audit_fields() RETURNS trigger AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    NEW.created_date := COALESCE(NEW.created_date, now());
    NEW.created_by   := COALESCE(NEW.created_by, current_setting('app.current_account_id', true), 'system');
  END IF;
  NEW.last_modified_date := now();
  NEW.last_modified_by   := COALESCE(current_setting('app.current_account_id', true), NEW.last_modified_by, NEW.created_by, 'system');
  RETURN NEW;
END
$$ LANGUAGE plpgsql;

-- =====================================================
-- 5. Cars Table
-- =====================================================

CREATE TABLE IF NOT EXISTS car.cars (
  -- Primary key
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- Basic vehicle information
  brand VARCHAR(100) NOT NULL,
  model VARCHAR(100) NOT NULL,
  registration_number CITEXT NOT NULL UNIQUE, -- Case-insensitive unique
  description TEXT,
  image_url TEXT,

  -- Specifications
  seats SMALLINT NOT NULL DEFAULT 5,
  transmission_type transmission_type,
  fuel_type fuel_type,
  category vehicle_category NOT NULL,
  daily_price NUMERIC(10,2) NOT NULL CHECK (daily_price >= 0),

  -- Ownership and operational flags
  owner_id VARCHAR(255) NOT NULL, -- References identity.accounts(id) ON DELETE RESTRICT
  archived BOOLEAN NOT NULL DEFAULT FALSE,
  shareable BOOLEAN NOT NULL DEFAULT TRUE,

  -- Audit fields
  created_date TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_modified_date TIMESTAMPTZ,
  created_by VARCHAR(255) NOT NULL DEFAULT 'system',
  last_modified_by VARCHAR(255),

  -- Constraints
  CHECK (seats > 0)
);

-- =====================================================
-- 6. Audit Trigger for Cars Table
-- =====================================================

CREATE TRIGGER trg_cars_audit
BEFORE INSERT OR UPDATE ON car.cars
FOR EACH ROW EXECUTE FUNCTION public.set_audit_fields();

-- =====================================================
-- 7. Indexes for Performance
-- =====================================================

-- Index on owner_id for owner-based queries
CREATE INDEX IF NOT EXISTS idx_cars_owner_id ON car.cars(owner_id);

-- Composite index for brand + price sorting
CREATE INDEX IF NOT EXISTS idx_cars_brand_price ON car.cars(brand, daily_price);

-- Composite index for category + price filtering
CREATE INDEX IF NOT EXISTS idx_cars_category_price ON car.cars(category, daily_price);

-- Partial index for public listings (shareable AND NOT archived)
CREATE INDEX IF NOT EXISTS idx_cars_shareable_active 
  ON car.cars(category, daily_price) 
  WHERE shareable = TRUE AND archived = FALSE;

-- Partial index for brand-based public listings
CREATE INDEX IF NOT EXISTS idx_cars_shareable_brand_price 
  ON car.cars(brand, daily_price) 
  WHERE shareable = TRUE AND archived = FALSE;

-- =====================================================
-- 8. Outbox Table for Event Sourcing
-- =====================================================

CREATE TABLE IF NOT EXISTS car.outbox_event (
  id UUID PRIMARY KEY,
  aggregate_type VARCHAR(100) NOT NULL,
  aggregate_id VARCHAR(100) NOT NULL,
  payload JSONB NOT NULL,
  headers JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  published_at TIMESTAMPTZ,
  status VARCHAR(20) NOT NULL DEFAULT 'NEW', -- NEW | PUBLISHED | FAILED
  CONSTRAINT chk_car_outbox_status CHECK (status IN ('NEW', 'PUBLISHED', 'FAILED'))
);

-- Indexes for outbox processing
CREATE INDEX IF NOT EXISTS idx_car_outbox_status_created ON car.outbox_event(status, created_at);
CREATE INDEX IF NOT EXISTS idx_car_outbox_new ON car.outbox_event(status) WHERE status = 'NEW';

-- =====================================================
-- 9. Row-Level Security (RLS) - Optional
-- =====================================================

-- Enable RLS on cars table
ALTER TABLE car.cars ENABLE ROW LEVEL SECURITY;

-- Policy: Owners can UPDATE/DELETE their own cars
CREATE POLICY car_cars_update_delete ON car.cars
  FOR UPDATE, DELETE USING (owner_id = current_setting('app.current_account_id', true));

-- Policy: Owners can INSERT cars with their own owner_id
CREATE POLICY car_cars_insert ON car.cars
  FOR INSERT WITH CHECK (owner_id = current_setting('app.current_account_id', true));

-- Policy: SELECT is public for shareable cars, or owner for non-shareable
CREATE POLICY car_cars_select ON car.cars
  FOR SELECT USING (shareable = TRUE OR owner_id = current_setting('app.current_account_id', true));

-- =====================================================
-- 10. Service Role and Permissions
-- =====================================================

-- Create service role if not exists
DO $$ BEGIN 
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'car_service') THEN 
    CREATE ROLE car_service NOLOGIN; 
  END IF; 
END $$;

-- Grant schema usage
GRANT USAGE ON SCHEMA car TO car_service;

-- Grant table permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA car TO car_service;

-- Grant sequence permissions (for IDENTITY columns)
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA car TO car_service;

-- Default privileges for future tables (run as schema owner)
-- ALTER DEFAULT PRIVILEGES IN SCHEMA car GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO car_service;
-- ALTER DEFAULT PRIVILEGES IN SCHEMA car GRANT USAGE, SELECT ON SEQUENCES TO car_service;

-- =====================================================
-- End of Migration V1
-- =====================================================
