package com.services.rental_service.dto;

import jakarta.validation.constraints.Future;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;

/**
 * Data Transfer Object for creating a new rental.
 * <p>
 * All fields except idempotencyKey are required.
 * Validation rules:
 * <ul>
 *   <li>pickupDatetime must be in the future</li>
 *   <li>returnDatetime must be after pickupDatetime (validated in service layer)</li>
 *   <li>carsId must exist in car-service (validated in service layer)</li>
 * </ul>
 * </p>
 *
 * @author Car Sharing Team
 * @version 1.0
 * @since 2025-01-09
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class CreateRentalRequest {

    /**
     * ID of the car to rent.
     * Foreign key reference to car.cars.
     */
    @NotNull(message = "Car ID is required")
    private Long carsId;

    /**
     * Desired pickup datetime (start of rental period).
     * Must be in the future at creation time.
     */
    @NotNull(message = "Pickup datetime is required")
    @Future(message = "Pickup datetime must be in the future")
    private Instant pickupDatetime;

    /**
     * Desired return datetime (end of rental period).
     * Must be after pickupDatetime.
     */
    @NotNull(message = "Return datetime is required")
    private Instant returnDatetime;

    /**
     * Pickup location (address or coordinates).
     * Optional, can be inferred from car's current location.
     */
    private String pickupLocation;

    /**
     * Expected return location (address or coordinates).
     * Optional, can be updated at return time.
     */
    private String returnLocation;

    /**
     * Idempotency key for duplicate request prevention.
     * Recommended: UUID generated by client.
     * If provided, must be unique per (renter_id, idempotency_key).
     */
    private String idempotencyKey;
}
