-- Flyway migration V1: Initialize pricing schema with pricing_rule table and constraints
-- Date: 2025-11-06
-- Author: Car Sharing Team
-- Description: Creates the pricing schema with pricing rules table, temporal constraints,
--              indexes for performance, and audit infrastructure.

-- ==================== Schema & Extensions ====================

-- Create pricing schema
CREATE SCHEMA IF NOT EXISTS pricing;

-- Install required extensions
CREATE EXTENSION IF NOT EXISTS btree_gist; -- Required for EXCLUDE constraints with '=' operator on btree types
CREATE EXTENSION IF NOT EXISTS citext;     -- Case-insensitive text (not used here, but ensures consistency with other schemas)

-- ==================== Enum Types ====================

-- Pricing unit enum (shared type, idempotent creation)
DO $$ BEGIN
  PERFORM 1 FROM pg_type WHERE typname = 'pricing_unit';
  IF NOT FOUND THEN 
    CREATE TYPE pricing_unit AS ENUM ('MINUTE', 'HOUR', 'DAY'); 
  END IF;
END $$;

-- Vehicle category enum (shared type, idempotent creation)
DO $$ BEGIN
  PERFORM 1 FROM pg_type WHERE typname = 'vehicle_category';
  IF NOT FOUND THEN 
    CREATE TYPE vehicle_category AS ENUM ('ECONOM', 'STANDARD', 'PREMIUM'); 
  END IF;
END $$;

-- ==================== Audit Trigger Function ====================

-- Function to auto-populate created/modified audit fields
-- Note: Uses GUC 'app.current_account_id' set by application per request
CREATE OR REPLACE FUNCTION public.set_audit_fields() RETURNS trigger AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    NEW.created_date := COALESCE(NEW.created_date, now());
    NEW.created_by   := COALESCE(NEW.created_by, current_setting('app.current_account_id', true), 'system');
  END IF;
  NEW.last_modified_date := now();
  NEW.last_modified_by   := COALESCE(current_setting('app.current_account_id', true), NEW.last_modified_by, NEW.created_by, 'system');
  RETURN NEW;
END
$$ LANGUAGE plpgsql;

-- ==================== Pricing Rule Table ====================

CREATE TABLE IF NOT EXISTS pricing.pricing_rule (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  -- Pricing configuration
  unit pricing_unit NOT NULL,
  vehicle_category vehicle_category NOT NULL,
  price_per_unit NUMERIC(10,2) NOT NULL CHECK (price_per_unit >= 0),
  
  -- Duration constraints (optional)
  min_duration INTERVAL,   -- Minimum rental duration
  max_duration INTERVAL,   -- Maximum rental duration
  
  -- Operational policies (optional)
  cancellation_window INTERVAL,                      -- Free cancellation window before pickup
  late_return_penalty_percent NUMERIC(5,2) CHECK (
    late_return_penalty_percent IS NULL OR 
    (late_return_penalty_percent BETWEEN 0 AND 100)
  ),
  
  -- Temporal validity (effective_from is required, effective_to is optional for indefinite rules)
  effective_from TIMESTAMPTZ NOT NULL,
  effective_to TIMESTAMPTZ,
  
  -- Generated column for temporal constraint enforcement
  -- This tstzrange column is auto-computed and used by the EXCLUDE constraint
  effective_period tstzrange GENERATED ALWAYS AS (
    tstzrange(effective_from, COALESCE(effective_to, 'infinity'::timestamptz), '[)')
  ) STORED,
  
  -- Active flag (soft-disable rules without deletion)
  active BOOLEAN NOT NULL DEFAULT TRUE,
  
  -- Audit fields (auto-populated by trigger and JPA Auditing)
  created_date TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_modified_date TIMESTAMPTZ,
  created_by VARCHAR(255) NOT NULL DEFAULT 'system',
  last_modified_by VARCHAR(255),
  
  -- Check constraints
  CONSTRAINT chk_pricing_effective_order 
    CHECK (effective_to IS NULL OR effective_to > effective_from),
  CONSTRAINT chk_pricing_duration_bounds 
    CHECK (max_duration IS NULL OR min_duration IS NULL OR max_duration >= min_duration),
  
  -- EXCLUDE constraint: Prevents overlapping rules for same (vehicle_category, unit) during same time period
  -- Uses btree_gist extension for '=' operator on enums and '&&' (overlaps) operator on tstzrange
  CONSTRAINT ex_pricing_no_overlap 
    EXCLUDE USING gist (
      vehicle_category WITH =,
      unit             WITH =,
      effective_period WITH &&
    )
);

-- Add trigger for audit fields
CREATE TRIGGER trg_pricing_audit
BEFORE INSERT OR UPDATE ON pricing.pricing_rule
FOR EACH ROW EXECUTE FUNCTION public.set_audit_fields();

-- ==================== Indexes ====================

-- Primary lookup index: Active rules by (category, unit)
-- Used by findActiveRule() repository method (most frequent query)
CREATE INDEX IF NOT EXISTS idx_pricing_rule_lookup 
  ON pricing.pricing_rule(vehicle_category, unit, active);

-- GIST index on effective_period for temporal queries
-- Supports fast overlap detection and validity window queries
CREATE INDEX IF NOT EXISTS idx_pricing_rule_period_active 
  ON pricing.pricing_rule USING GIST (effective_period) 
  WHERE active = TRUE;

-- ==================== Outbox Table (for Event Sourcing) ====================

-- Outbox table for publishing domain events via Outbox pattern
CREATE TABLE IF NOT EXISTS pricing.outbox_event (
  id UUID PRIMARY KEY,
  aggregate_type VARCHAR(100) NOT NULL,
  aggregate_id   VARCHAR(100) NOT NULL,
  payload JSONB NOT NULL,
  headers JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  published_at TIMESTAMPTZ,
  status VARCHAR(20) NOT NULL DEFAULT 'NEW', -- NEW | PUBLISHED | FAILED
  CONSTRAINT chk_pricing_outbox_status CHECK (status IN ('NEW','PUBLISHED','FAILED'))
);

-- Indexes for outbox processing
CREATE INDEX IF NOT EXISTS idx_pricing_outbox_status_created 
  ON pricing.outbox_event(status, created_at);

CREATE INDEX IF NOT EXISTS idx_pricing_outbox_new 
  ON pricing.outbox_event(status) 
  WHERE status = 'NEW';

-- ==================== Roles & Permissions ====================

-- Create service role (if not exists)
DO $$ BEGIN 
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'pricing_service') THEN 
    CREATE ROLE pricing_service NOLOGIN; 
  END IF; 
END $$;

-- Grant schema usage
GRANT USAGE ON SCHEMA pricing TO pricing_service;

-- Grant table permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA pricing TO pricing_service;

-- Grant sequence permissions (for IDENTITY columns)
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA pricing TO pricing_service;

-- Future tables will inherit permissions (execute as schema owner)
-- ALTER DEFAULT PRIVILEGES IN SCHEMA pricing GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO pricing_service;

-- ==================== Comments for Documentation ====================

COMMENT ON SCHEMA pricing IS 'Schema for pricing rules and tariff management';
COMMENT ON TABLE pricing.pricing_rule IS 'Pricing rules defining cost structure for vehicle rentals';
COMMENT ON COLUMN pricing.pricing_rule.unit IS 'Time unit for pricing: MINUTE, HOUR, or DAY';
COMMENT ON COLUMN pricing.pricing_rule.vehicle_category IS 'Vehicle category: ECONOM, STANDARD, or PREMIUM';
COMMENT ON COLUMN pricing.pricing_rule.price_per_unit IS 'Cost per single unit of time (e.g., €12.00 per HOUR)';
COMMENT ON COLUMN pricing.pricing_rule.min_duration IS 'Minimum rental duration (optional, ISO-8601 interval)';
COMMENT ON COLUMN pricing.pricing_rule.max_duration IS 'Maximum rental duration (optional, ISO-8601 interval)';
COMMENT ON COLUMN pricing.pricing_rule.cancellation_window IS 'Free cancellation window before pickup (optional)';
COMMENT ON COLUMN pricing.pricing_rule.late_return_penalty_percent IS 'Late return penalty as % of base cost (0-100%)';
COMMENT ON COLUMN pricing.pricing_rule.effective_from IS 'Start of rule validity (inclusive)';
COMMENT ON COLUMN pricing.pricing_rule.effective_to IS 'End of rule validity (exclusive, NULL means indefinite)';
COMMENT ON COLUMN pricing.pricing_rule.effective_period IS 'Auto-generated tstzrange for EXCLUDE constraint enforcement';
COMMENT ON COLUMN pricing.pricing_rule.active IS 'Whether the rule is active (soft-disable flag)';
COMMENT ON CONSTRAINT ex_pricing_no_overlap ON pricing.pricing_rule IS 'Prevents overlapping rules for same (category, unit) during same time period';
COMMENT ON TABLE pricing.outbox_event IS 'Outbox table for publishing pricing change events';
